### ISSUE TITLE
Decide if a persistence layer is needed and how to update historical data

### ISSUE THREAD

**Issue by ognjenkurtic** [carbonara-coinpensator/carbonara-backend#6]

**Comment by ognjenkurtic** [comment]
We are currently either fetching data from the public APIs or reading static data which was manually populated. The goal of this issue is to come to the agreement on how to handle this in the future. 
Do we want to persist historical data and use it for the calculcation while periodically updating it?
Any other ideas?

**Comment by sulejmank** [comment]
https://github.com/mbdavid/LiteDB
